spring:
  profiles:
    active: local # default
    group:
      local:
        - common
      test:
        - common
---

logging.level:
  joo.project.my3d: debug
spring:
  config.activate.on-profile: local

---

spring:
  config.activate.on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
