spring:
  profiles:
    active: local # default
    group:
      local:
        - common
      test:
        - common
---

logging.level:
  joo.project.my3d: debug
spring:
  config.activate.on-profile: local
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
  devtools.livereload:
    enabled: true
    port: 35730
  mvc:
    view:
      suffix: .jsp

---

spring:
  config.activate.on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true
  sql.init.mode: always
